apiVersion: v1
kind: Service
metadata:
  name: airports-service
spec:
  selector:
    app: fastapi-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30001
  type: NodePort
