apiVersion: apps/v1
kind: Deployment
metadata:
  name: airports-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airports
  template:
    metadata:
      labels:
        app: airports
    spec:
      containers:
      - name: airports-container
        image: fastapi-app:latest  # Substitua pelo nome da imagem no DockerHub, se necessário
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://asa:1989@<database-service>:5432/trabalho_final"
